const films = [
    {
        id:'1',
        name: 'The Banshees of Inisherin',
        image: 'https://www.themoviedb.org/t/p/w1280/dpeR3ue0Q93Rk8jhE2DzVPMRGIm.jpg',
        director: 'Martin McDonagh',
        genre: 'Drama',
        rating: 'R',
        score: 8.2,
        time: 114,
    },{
        id:'2',
        name: 'The Fabelmans',
        image: 'https://www.themoviedb.org/t/p/w1280/d2IywyOPS78vEnJvwVqkVRTiNC1.jpg',
        director: 'Steven Spielberg',
        genre: 'Drama',
        rating: 'PG-13',
        score: 8.2,
        time: 151,
    },{
        id:'3',
        name: 'TÁR',
        image: 'https://www.themoviedb.org/t/p/w1280/dRVAlaU0vbG6hMf2K45NSiIyoUe.jpg',
        director: 'Todd Field',
        genre: 'Drama',
        rating: 'R',
        score: 7.8,
        time: 158,
    },{
        id:'4',
        name: 'Everything Everywhere All at Once',
        image: 'https://www.themoviedb.org/t/p/w1280/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
        director: 'Daniel Kwan, Daniel Scheinert',
        genre: 'Sci-Fi',
        rating: 'R',
        score: 8.1,
        time: 139,
    },{
        id:'5',
        name: 'Top Gun: Maverick',
        image: 'https://www.themoviedb.org/t/p/w1280/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
        director: 'Joseph Kosinski',
        genre: 'Action',
        rating: 'PG-13',
        score: 8.4,
        time: 131,
    },{
        id:'6',
        name: 'Women Talking',
        image: 'https://www.themoviedb.org/t/p/w1280/2T6NRABkeFGMWVy1TNNc6yplaiy.jpg',
        director: 'Sarah Polley',
        genre: 'Drama',
        rating: 'PG-13',
        score: 7.8,
        time: 104,
    },{
        id:'7',
        name: 'The Woman King',
        image: 'https://www.themoviedb.org/t/p/w1280/438QXt1E3WJWb3PqNniK0tAE5c1.jpg',
        director: 'Gina Prince-Blythewood',
        genre: 'Action',
        rating: 'PG-13',
        score: 6.7,
        time: 134,
    },{
        id:'8',
        name: 'Elvis',
        image: 'https://www.themoviedb.org/t/p/w1280/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg',
        director: 'Baz Luhrmann',
        genre: 'Drama',
        rating: 'PG-13',
        score: 7.4,
        time: 159,
    },{
        id:'9',
        name: 'Glass Onion: A Knives Out Mystery',
        image: 'https://www.themoviedb.org/t/p/w1280/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg',
        director: 'Rian Johnson',
        genre: 'Mystery',
        rating: 'PG-13',
        score: 8.0,
        time: 139,
    },{
        id:'10',
        name: 'RRR',
        image: 'https://www.themoviedb.org/t/p/w1280/kdO4JtO5DnIMyLymQv8C8Ol1CzA.jpg',
        director: 'S.S. Rajamouli',
        genre: 'Action',
        rating: 'PG-13',
        score: 8.0,
        time: 187,
    },{
        id:'11',
        name: 'Triangle of Sadness',
        image: 'https://www.themoviedb.org/t/p/w1280/fgy78BLl0gk8OzTWHZyGrSlIEON.jpg',
        director: 'Ruben Östlund',
        genre: 'Drama',
        rating: 'R',
        score: 7.7,
        time: 140,
    },{
        id:'12',
        name: 'Living',
        image: 'https://www.themoviedb.org/t/p/w1280/zUJcp0rpUqp2GSk7t9jvAiZsXtM.jpg',
        director: 'Oliver Hermanus',
        genre: 'Drama',
        rating: 'PG-13',
        score: 7.6,
        time: 162,
    }
]

export default films;